### ISSUE TITLE
Styleguide : add components (batch 2)

### ISSUE THREAD

**Issue by Skaant** [Skaant/rimarok-2#36]
Add the following components to the Styleguide page :
* [x] #25 
* [x] #31 
* [x] #30 
* [x] #6 
* [x] #33

**Comment by Tim-jn** [comment]
Si je dois faire des modifs sur les composants, je recrée une branche ou je les fais directement sur cette branche ?

**Comment by Skaant** [comment]
In left panel : added styleguide link
In right panel : added contact label & link
