### ISSUE TITLE
Fixes batch 1

### ISSUE THREAD

**Issue by Skaant** [Skaant/rimarok-2#68]
Make these fixes **on the same branch and the same PR :**

- [x] Fix : Carousel > Project is going above Navbar
   ![image](https://user-images.githubusercontent.com/7300148/178690755-06673b73-a8b2-4528-a2a9-13ba934a36df.png)
- [x] Navbar sub-menu mobile : add `mb` under Prestation box,
- [x] Footer : reverse col order mobile.

**Comment by Tim-jn** [comment]
@Skaant Carousel et NavBar on étés modifiés dans la PR "Fix navbar" et Footer dans la PR "Add 5 last articles to Footer"
